# Generated by Django 4.1.1 on 2022-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='create_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
